name: deploy package to the Maven Central Repository
on:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
#          cache: 'maven'
          java-version: '17'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Import GPG private key
        env:
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        run: |
          f=`mktemp`
          echo "${MAVEN_GPG_PRIVATE_KEY}" > "$f"
          gpg --batch --import-options import-show --import "$f"
      - run: |          
          mvn versions:set -DnewVersion=$GITHUB_REF_NAME 
          mvn -B package -D skipTests --file pom.xml --no-transfer-progress
          mvn verify gpg:sign -Dgpg.passphrase=$MAVEN_GPG_PASSPHRASE 
          mvn deploy --no-transfer-progress
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}